# VulKan Multi-Device  Benchmark Configuration

# Matrix dimensions 1, 2, 3 (default: 2)
dimention = 1

# Maximum matrix size (default: 1024)
matrix-size = 2097152
#GA104: L1 128kb, L2 4096kb
#1048576, 2097152, 4194304

# Start matrix size (default: 32)
matrix-start-size = 16384
#4096 8192 16384 32768 65536

# Matrix increment step (default: 32)
matrix-increment-step = 16384

# Data type: fp16, int16, fp32, int32 (default: fp16)
data-type = int8, int16, int32

# Operator: mul, add, sub, div, mad, mat-mul, mat-add, mat-sub, mat-div, mat-mad, default: mul)
#operator = mul, add,sub,div,mad
operator = mat-mul, mat-add, mat-sub, mat-div, mat-mad

# Benchmarking iterations (default: 10)
iterations = 10

# Vulkan device index (default: 0)
device = 0,2

# LACT profile name (default: 210_405) 
#A4: 0_210_405, 0_default, 0_1710_8500
#HX: 2_210_405, 2_default, 2_1905_11350
lact = 0_210_405,2_210_405

# Save results to CSV file (default: false)
save-csv = true

# Benchmark multiple devices side-by-side (default: false)
multi-bench = true

# Cooldown pause between tests in seconds (default: 0)
pause = 0

